#!/usr/bin/env bash
# A bash script that displays information about subdomains

print_domain_subdomain() {
    local domain="$1"
    local subdomain="$2"

    dig "$subdomain.$domain" +short | awk -v sub="$subdomain" -v dom="$domain" 'BEGIN { printf("The subdomain %s is ", sub); }
        NR == 1 { printf("a %s record and points to %s\n", $1, $2); }'
}

if [[ "$#" -eq 2 ]]; then
    print_domain_subdomain "$1" "$2"
else
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        print_domain_subdomain "$1" "$subdomain"
    done
fi

