#!/usr/bin/env bash
# This script configures the domain zone so that the subdomain www
# points to the load balancer IP (lb-01)

print_domain_subdomain () {        
    # Print the subdomain, record type, and target IP address
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 2 ]; then
    # If two arguments are provided, print information for the specified subdomain and domain
    print_domain_subdomain "$2.$1" "$2"
else
    # Print information for predefined subdomains and the main domain
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
    print_domain_subdomain "lb-01.$1" "lb-01"
fi

