#!/usr/bin/env bash

# Print domains and subdomains

print_domain_subdomain() {
    # Use lowercase variable names
    local domain="$1"
    local subdomain="$2"

    # Retrieve DNS information using dig and extract relevant details using grep and awk
    dig "$domain" | grep -A1 'ANSWER SECTION:' | sed -r "s/$domain/$subdomain/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1" "$2"
else
    # Use lowercase subdomains for consistency
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
