#!/usr/bin/env bash
# Configure ufw firewall to allow specific incoming TCP ports
# (#22, 443, and 80) while blocking all other incoming traffic.

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
