#!/usr/bin/env bash
# Configure Nginx to run as nginx user
pkill apache2
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i '/80/8080/g' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
