#!/usr/bin/env bash
# Configure Nginx to run as nginx user
pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/d\
efault
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0700 /etc/nginx/nginx.conf
service nginx restart
